ДЗ1
sideov/formal-lang-course pull request #1
Opened 2024-02-09 23:52 UTC by sideov

Были выполнены все задания. Работа готова к проверке

2024-02-17 20:47 UTC, sideov commented
Были сделаны некоторые изменения, связанные с настройкой тестов.

2024-03-01 17:10 UTC, WoWaster requested changes

2024-03-01 17:10 UTC, WoWaster commented on .github/workflows/run_tests.yml
> +          python -m pytest -s tests/
Используйте, пожалуйста, данный скрипт: https://github.com/sideov/formal-lang-course/blob/main/scripts/run_tests.py 
Иначе я в CI не вижу какие тесты у вас вообще запустились :cry:

2024-03-06 19:16 UTC, sideov commented
Добрый вечер! Изменил команду запуска тестов и версию Python.

2024-03-07 18:36 UTC, WoWaster approved these changes

2024-03-10 03:52 UTC, merged