HW7
sideov/formal-lang-course pull request #10
Opened 2024-04-14 01:08 UTC by sideov

Задание выполнено. Тесты взял из прошлой домашки

2024-04-17 16:48 UTC, sideov commented
Подтянул новые тесты

2024-04-18 11:30 UTC, WoWaster requested changes
И тесты к 4 задачке у вас почему-то здесь не проходят. Поправьте, пожалуйста

2024-04-18 11:30 UTC, WoWaster commented on project/task7.py
> +    return CFG(productions=set(productions), start_symbol=Variable("S"))
А вам точно здесь эта функция нужна? Она же есть в шестой домашке

2024-04-18 11:30 UTC, WoWaster commented on project/task7.py
> +def cfpq_with_matrix(
Я, конечно, всё понимаю, что разреженные матрицы на словарях пишутся элементарно, но просили использовать scipy.

2024-04-27 08:03 UTC, WoWaster approved these changes

2024-04-27 17:35 UTC, merged