HW-2
sideov/formal-lang-course pull request #4
Opened 2024-02-28 13:13 UTC by sideov

Все задания выполнены. Работа готова к проверке

2024-03-06 19:10 UTC, sideov commented
Изменил команду для запуска тестов

2024-03-07 18:56 UTC, WoWaster requested changes
Подтяните изменения из первый домашней работы сюда, чтобы я не видел в Files Changed изменений из неё

2024-03-07 18:56 UTC, WoWaster commented on tests/autotests/test_task3.py
Удалять автотесты не нужно, они сам пропускаются, если нет решения

2024-03-10 04:27 UTC, sideov commented
Изменения подтянул

2024-03-10 07:59 UTC, WoWaster approved these changes

2024-03-10 13:55 UTC, merged