Hw3
sideov/formal-lang-course pull request #6
Opened 2024-03-11 00:42 UTC by sideov

2024-03-11 00:55 UTC, sideov commented
Я сделал pull, у меня все пропало и старый request почему-то закрылся)) Поэтому я создал новый request

2024-03-11 07:55 UTC, WoWaster requested changes

2024-03-11 07:55 UTC, WoWaster commented on project/task3.py
> +    intersected_fa = intersect_automata(graph_fa, regex_fa)
А у вас здесь типы сошлись?

2024-03-11 10:28 UTC, sideov commented on project/task3.py
> +    intersected_fa = intersect_automata(graph_fa, regex_fa)
Поправил

2024-03-11 12:54 UTC, WoWaster requested changes
А теперь у вас тесты к этой задачке скипаются :)

2024-03-11 22:52 UTC, sideov commented
Поправил

2024-03-12 07:52 UTC, WoWaster approved these changes

2024-03-12 12:17 UTC, merged