HW5
sideov/formal-lang-course pull request #8
Opened 2024-03-20 20:03 UTC by sideov

2024-03-26 11:03 UTC, WoWaster requested changes
Во-первых, подтяните остальные ветки сюда. 
Во-вторых, опишите как сие чудо запускать. Мой VS Code попросил ещё пару зависимостей, который вы не дописали в requirements.txt, а потом просто ничего не смог запустить с такой ошибкой
![image](https://github.com/sideov/formal-lang-course/assets/11057754/6242fe4e-8d1b-4b55-83b7-23919112fee4)
Напишите инструкцию, а лучше ссылку на Google Collab. 
В-третьих, внимательно прочитайте, чего надо написать в отчете!

2024-05-23 23:18 UTC, sideov commented
Отчет поправил

2024-05-26 09:30 UTC, WoWaster requested changes
В общем-то

2024-05-26 09:30 UTC, WoWaster commented on project/task5.ipynb
> +    "import matplotlib.pyplot as plt\n",
Я всё ещё не могу запустить это локально, как минимум он хочется `ipython` и `matplotlib` дальше меня не хватило

2024-05-26 09:30 UTC, WoWaster commented on project/task5.ipynb
> +    "print(platform.processor())"
Характеристики своего компьютера лучше руками вписать: важной информации типа модели процессора и характеристик памяти тут нет

2024-05-26 09:30 UTC, WoWaster commented on project/task5.ipynb
> +    "        print(f\"{matrix_class_mapper(matrix_class)} time: {times[matrix_class_mapper(matrix_class)]/num_cases}\")\n",
Забавно, что результата это print'а я не вижу, а без него вообще невозможно сказать правда ли lil матрицы лучше. Кроме того, без отклонения на чиселки смотреть бесполезно. 
Нарисуйте здесь, пожалуйста, график, чтобы было красиво и наглядно

2024-05-26 09:30 UTC, WoWaster commented on project/task5.ipynb
> +   ],
К этому коду так же применяются слова про отклонение. Возможно гистограмма, где для каждого числа вершин будет по два столбца, соответствующие алгоритмам, график будет легче читаться

2024-05-26 16:06 UTC, sideov commented
В общем. Надо было сразу писать в колабе, а то я конечно вас запутал и сам запутался. Вот ссылка: https://colab.research.google.com/drive/1h6DVX_T2ntBKHmqCJSuEsws1i1der2xi#scrollTo=B1pj1BFeckE8. Добавил гистаграммы с усами, показывающие среднее время работы и стандартное отклонение выборки от нее.

2024-05-26 16:40 UTC, WoWaster commented
Можете, пожалуйста, в настройках общего доступа разрешить комментирование?

2024-05-26 19:05 UTC, sideov commented
> Можете, пожалуйста, в настройках общего доступа разрешить комментирование?

Сделал

2024-05-26 19:15 UTC, WoWaster requested changes
Спасибо! Оставил комментарии прямо в коллабе

2024-05-26 23:06 UTC, sideov commented
Замечания учел

2024-05-27 09:36 UTC, WoWaster requested changes
Оставил ещё комментариев

2024-05-27 10:38 UTC, sideov commented
Готово

2024-05-27 13:28 UTC, WoWaster commented
В первом случае у вас `num_cases = 1` :(

2024-05-27 14:40 UTC, sideov commented
> В первом случае у вас `num_cases = 1` :(

Посмотрел, вроде бы там везде 10 стоит

2024-05-30 13:01 UTC, WoWaster commented
Я не понял чего произошло, но я не вижу ни одной диаграмки. Можете заного запустить всё?

2024-05-31 10:29 UTC, sideov commented
> Я не понял чего произошло, но я не вижу ни одной диаграмки. Можете заного запустить всё?

Сделал

2024-06-02 17:41 UTC, WoWaster commented
Меня гугл с ума сводит или там правда всё ещё графиков нет?

2024-06-02 21:30 UTC, sideov commented
> Меня гугл с ума сводит или там правда всё ещё графиков нет?

Теперь должно быть все норм

2024-06-03 09:50 UTC, WoWaster commented
Оставил ещё комментариев

2024-06-05 19:22 UTC, sideov commented
> https://colab.research.google.com/drive/1h6DVX_T2ntBKHmqCJSuEsws1i1der2xi?usp=sharing

Сделал

2024-06-06 14:32 UTC, sideov commented
> Оставил ещё комментариев

Сделал

2024-06-08 10:40 UTC, WoWaster commented
Первого графика нет :(

2024-06-09 16:37 UTC, sideov commented
> https://colab.research.google.com/drive/1h6DVX_T2ntBKHmqCJSuEsws1i1der2xi?usp=sharing

Теперь должен появиться

2024-06-11 11:14 UTC, WoWaster commented
Сейчас в коллабе висят только актуальные замечания. Большинство из них оставлены некоторое время назад и всё ещё не исправлены. Пожалуйста, пройдитесь по **всем** комментариям, которые сейчас висят в коллабе и исправьте их.

2024-06-18 08:41 UTC, sideov commented
Исправил

2024-06-18 09:36 UTC, WoWaster approved these changes
С моей точки зрения выглядит ок. Призываю Семёна Вячеславовича

2024-06-23 13:01 UTC, sideov commented
?

2024-06-24 11:51 UTC, gsvgit commented
Не в давайсь в косяки текста (коих много). Нужно нормально проанализировать причину наблюдаемого поведения. У Вас получается, что алгоритм, который должен делать существенно меньше работы, работает существенно хуже. Почему? То же самое про матрицы. Отдельный разговор, что для исследования взяты чуть ли не самые маленькие графы. А время работы при этом какое-то гигантское.

2024-06-24 19:41 UTC, sideov commented
Добрый вечер!
1. По поводу того, что алгоритм, основанный на транзитивном замыкании работает быстрее, чем алгоритм, основанный на BFS. Я вижу объяснение этому явлению в том, что при вычислении транзитивного замыкания мы занимаемся умножением матрицы самой на себя много раз. Операция умножения умножения матриц очень хорошо векторизуется и оптимизируется процессором и в итоге суммарное процессорное время, затраченное на эти операции становится значительно меньше, чем время, затраченное на многократное пересчитывание фронта

2024-06-24 19:49 UTC, sideov commented
2. Что касается матриц. В колабе дано развернутое объяснение тому, почему lil матрица дает более хорошие результаты по сравнению со всеми остальными матрицами. Если вкратце, то это связано с тем фактом, что она представляет собой связный список элементов в строках - это позволяет быстро выполнять умножение в условиях сильной разреженности. dok матрица представляет собой просто хэш-таблицу - из за этого все арифметические операции с ней выполняются медленно.

2024-12-02 11:43 UTC, closed without merging